export const INITIAL_TODOS_PAGE = 1;
export const TODOS_PER_PAGE = 3;

export const SET_CURRENT_TODOS_PAGE = "SET_CURRENT_TODOS_PAGE";
export const SET_TOTAL_TODO_PAGES_AMOUNT = "SET_TOTAL_TODO_PAGES_AMOUNT";
